apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskdemodev
  name: flaskdemodev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskdemodev
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskdemodev
    spec:
      containers:
      - image: skinnysydcontainersregistry.azurecr.io/pylocaltestpfe:27
        name: flaskdemodev
        resources:
          requests:
            memory: "256Mi"  # Request 256 megabytes of memory
            cpu: "0.1"       # Request 0.1 CPU units
          limits:
            memory: "512Mi"  # Limit memory usage to 512 megabytes
            cpu: "0.3"       # Limit CPU usage to 0.5 CPU units
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: flaskdemodev
