apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flaskdemo.fullname" . }}
  labels:
    app: {{ include "flaskdemo.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flaskdemo.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flaskdemo.name" . }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          resources: {}
